### ISSUE TITLE
Update prod & QA ENV vars to use in QA script

### ISSUE THREAD

**Issue by codecakes** [Xcov19/qa-framework#34]

**Comment by akshathagujjar** [comment]
The readme file has been updated with the command to pass URL on execution in the command line. 

https://github.com/Xcov19/qa-framework/blob/main/README.md

**Comment by codecakes** [comment]
> The readme file has been updated with the command to pass URL on execution in the command line.
> 
> https://github.com/Xcov19/qa-framework/blob/main/README.md

The ENV settings have not been updated. This still needs to be done

**Comment by akshathagujjar** [comment]
> > The readme file has been updated with the command to pass URL on execution in the command line.
> > https://github.com/Xcov19/qa-framework/blob/main/README.md
> 
> The ENV settings have not been updated. This still needs to be done

Should the Dockerfile be updated to pick the URL from the environment?

**Comment by codecakes** [comment]
> > > The readme file has been updated with the command to pass URL on execution in the command line.
> > > https://github.com/Xcov19/qa-framework/blob/main/README.md
> > 
> > 
> > The ENV settings have not been updated. This still needs to be done
> 
> Should the Dockerfile be updated to pick the URL from the environment?

Hi @akshathagujjar 
@mgna7 is working on it.

**Comment by akshathagujjar** [comment]
The readme file has been updated with all the necessary commands to create and pass environment variables. The URL can be created and passed with an environment variable now. 
https://github.com/Xcov19/qa-framework/blob/main/README.md
